### ISSUE TITLE
Reason for replacing /etc/grub.d/10_linux?

### ISSUE THREAD

**Issue by ed-cooper** [dmoisset/hp-envy13#2]
I was following the steps but for Ubuntu 19.04, everything works fine until it comes to making the changes permanent where the version of grub-common for me was different.

Not wanting to risk bricking my laptop, I found a simpler solution of just using grub customiser to permanently add `acpi /boot/dsdt.aml` to my bootloader.

I was wondering if there was any reason you chose to replace the file manually as your method seems more complex and dangerous?

(Note that grub customiser didn't like the quotation marks in `acpi_osi=\"Windows 2009\""` and tried to remove them, causing an error, but manually editing the grub file and running update-grub again fixed the issue)

**Comment by csnewman** [comment]
Yeah bruv, what ya thincc yourr do'in?!

**Comment by dmoisset** [comment]
I chose that way because that's the one I knew about :) I'm not familiar with grub customiser, if you like you could submit a patch to the readme file detailing that approach so it can be shared with others.

Thanks for the feedback!

**Comment by ed-cooper** [comment]
Done

**Comment by dmoisset** [comment]
Merged. Thank you!
